name: TypeScript | Quality Assurance

on:
    push:
    pull_request:

defaults:
    run:
        shell: bash

jobs:
    unit-test:
        name: Unit Tests
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./typescript

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: bun install --frozen-lockfile
            - run: bun run workflow:test:unit

    benchmark-test:
        name: Benchmark Tests
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./typescript

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: bun install --frozen-lockfile
            - run: bun run workflow:test:benchmark

    install:
        name: Install via ${{ matrix.package_manager }} on Node ${{ matrix.node_version }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node_version: [22, 24]
                package_manager:
                    - npm
                    - pnpm
                    - yarn
                    - bun

        steps:
            - if: matrix.package_manager == 'npm'
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - if: matrix.package_manager == 'pnpm'
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - if: matrix.package_manager == 'pnpm'
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - if: matrix.package_manager == 'yarn'
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - if: matrix.package_manager == 'bun'
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: sleep 15

            - if: matrix.package_manager == 'npm'
              run: npm install qlogicae_aklot@latest

            - if: matrix.package_manager == 'pnpm'
              run: pnpm add qlogicae_aklot@latest

            - if: matrix.package_manager == 'yarn'
              run: yarn add qlogicae_aklot@latest

            - if: matrix.package_manager == 'bun'
              run: bun add qlogicae_aklot@latest
